@startuml
|Pengguna / Admin|
start
:Membuka Halaman Login;
if (Pilih Metode Login?) then (Manual)
  :Memasukkan Email & Password;
  
  |Sistem LMS|
  :Menerima Input Kredensial;
  :Validasi Data (Mengeksekusi Native Query PostgreSQL);
  
else (Google Auth)
  |Pengguna / Admin|
  :Klik "Login via Google";
  
  |Google Auth|
  :Proses Otentikasi Akun Google;
  
  |Sistem LMS|
  :Menerima dan Verifikasi Token JWT;
endif

|Sistem LMS|
if (Otentikasi Berhasil?) then (Ya)
  :Menghasilkan Sesi (JWT);
  :Mengarahkan langsung ke Home;
  stop
else (Tidak)
  :Menampilkan Pesan Error (Kredensial Salah / Gagal);
  |Pengguna / Admin|
  :Kembali ke Halaman Login;
  stop
endif
@enduml