@startuml
|Pengguna|
start
:Mengeklik Menu "Leaderboard / Ranked";

|Sistem LMS|
:Menerima Permintaan Halaman;
:Eksekusi Native Query 
(SELECT & ORDER BY total_xp DESC);
:Mengelompokkan Data Berdasarkan Kategori 
(Learner Terbaik & Creator Terbaik);
:Merender Tampilan Antarmuka;

|Pengguna|
:Melihat Peringkat Diri Sendiri & Orang Lain;
stop
@enduml